names = ["PSK", "SPK", "SSK", "MSK", "JSK"]
print(names)
print("----- Positive index -----")
print(names[0])
print(names[1])
print(names[2])
print(names[3])
print(names[4])
print("----- Negative index -----")
print(names[-1])
print(names[-2])
print(names[-3])
print(names[-4])
print(names[-5])
print("----- Range index -----")
print(f"Oldest 3: {names[0:3]}")
print(f"Girls (Odds) {names[0:5:2]}")
print(f"Boys (Evens) {names[1:5:2]}")
print(names[:-5])
print(names[:-4])
print(names[1:-3])
print(names[2:])
print(names[::1])
print("----- Replace names -----")
